"""Deterministic, source-grounded fertilizer guidance for Burkina Faso crops.

The doses below are NOT generated by the LLM. They are fixed values taken from
published Burkina Faso research / extension recommendations (INERA and peer-
reviewed Burkinabè journals), so the assistant never invents fertilizer numbers.
Each crop entry cites the source(s) backing its figures, and every answer ends
with a mandatory "confirmez avec votre agent" disclaimer.

Crop detection now routes through the ``core.crops`` registry (A1), so a question
about a recognized but unsupported crop (e.g. sésame) falls back to RAG.

Sources:
  - Int. J. Biol. Chem. Sci. (IJBCS), essais microdose INERA sur sorgho, mil et
    niébé au Burkina Faso — dose vulgarisée céréales : 100 kg/ha NPK (14-23-14)
    + 50 kg/ha urée ; niébé : 100 kg/ha NPK seul.
  - Revue Sciences et Techniques du Burkina — dose vulgarisée maïs : 150 kg/ha
    NPK (14-23-14) + 100 kg/ha urée ; fertilisation des légumineuses (arachide,
    niébé) : faible apport d'azote (~14 kg N/ha) suffisant, fumure organique
    recommandée.
"""

from core.crops import CROPS, resolve_crop, resolve_crops
from core.case import build_advice_case

SRC_IJBCS = {
    "title": "Recherche INERA - microdose Burkina",
    "type": "Outil engrais",
    "snippet": "Essais sur sorgho, mil et niébé: doses vulgarisées NPK/urée et options microdose.",
}
SRC_RSTB_MAIS = {
    "title": "Sciences et Techniques du Burkina - maïs",
    "type": "Outil engrais",
    "snippet": "Dose vulgarisée du maïs: NPK au semis et urée en couverture.",
}
SRC_RSTB_LEG = {
    "title": "Sciences et Techniques du Burkina - légumineuses",
    "type": "Outil engrais",
    "snippet": "Fertilisation prudente des légumineuses: faible azote, fumure organique et phosphate.",
}

for _source in (SRC_IJBCS, SRC_RSTB_MAIS, SRC_RSTB_LEG):
    _source["review_status"] = "Référence précise en attente de vérification agronomique"

DISCLAIMER = (
    "⚠️ Ce sont des recommandations générales issues de la recherche (INERA). "
    "Confirmez toujours avec votre agent agricole : la bonne dose dépend de votre "
    "sol, de la pluie et de vos moyens. Les références détaillées des doses restent "
    "à vérifier : ces repères ne sont pas une prescription pour votre parcelle."
)

# Canonical crop id -> grounded recommendation text + sources.
_RECOMMENDATIONS = {
    "sorgho": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14) au semis + 50 kg/ha "
            "d'urée (46 %) à la montaison.",
            "Microdose (plus économique) : 2 g de NPK par poquet (~62,5 kg/ha) au "
            "semis + 1 g d'urée par poquet (~31,25 kg/ha) à la montaison.",
        ],
        "sources": [SRC_IJBCS],
    },
    "mil": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14) au semis + 50 kg/ha "
            "d'urée (46 %) à la montaison.",
            "Microdose du mil : chiffres temporairement retirés, car les équivalences "
            "par poquet et par hectare doivent être vérifiées avec un agronome.",
        ],
        "sources": [SRC_IJBCS],
    },
    "mais": {
        "lines": [
            "Dose vulgarisée : 150 kg/ha de NPK (14-23-14) au semis + 100 kg/ha "
            "d'urée (46 %) en couverture.",
            "Le maïs est très exigeant : un sol pauvre donne de faibles rendements. "
            "La fumure organique et la rotation aident beaucoup.",
        ],
        "sources": [SRC_RSTB_MAIS],
    },
    "niebe": {
        "lines": [
            "Dose vulgarisée : 100 kg/ha de NPK (14-23-14), sans urée — le niébé "
            "est une légumineuse qui fixe l'azote de l'air.",
            "Un faible apport d'azote suffit ; la fumure organique améliore le "
            "rendement.",
        ],
        "sources": [SRC_IJBCS, SRC_RSTB_LEG],
    },
    "arachide": {
        "lines": [
            "L'arachide est une légumineuse : elle fixe l'azote de l'air, donc un "
            "faible apport d'azote (~14 kg N/ha) suffit.",
            "Privilégiez la fumure organique (fumier) et le phosphate ; évitez les "
            "fortes doses d'urée.",
        ],
        "sources": [SRC_RSTB_LEG],
    },
}

# Correct French article per crop (for "pour ... au Burkina Faso"), keyed by id.
_CROP_LABEL = {
    "sorgho": "le sorgho",
    "mil": "le mil",
    "mais": "le maïs",
    "niebe": "le niébé",
    "arachide": "l'arachide",
}

# Words that signal the user is asking about fertilizer / fertilization.
_FERTILIZER_KEYWORDS = (
    "engrais",
    "fumure",
    "fertilis",
    "npk",
    "urée",
    "uree",
    "dose d'engrais",
    "dose d engrais",
    "fertilizer",
    "microdose",
    "micro-dose",
)

# Phase B safety gate: keep every unverified figure out of public payloads until
# an agronomist records exact provenance for the active table.
NUMERIC_GUIDANCE_VERIFIED = False
WITHHELD_NOTICE = (
    "Les doses exactes sont temporairement retirées : leur source, leur "
    "formulation et leurs conditions d’application doivent encore être vérifiées "
    "par un agronome. Demandez la dose adaptée à votre agent agricole avant "
    "toute application."
)


def build_offline_fertilizer_payload() -> dict:
    """Return the canonical browser-offline fertilizer data.

    ``scripts/export_offline_fertilizer.py`` writes this payload to the PWA asset.
    Keeping the builder here makes the Python tool the only hand-edited source for
    doses, sources, aliases, labels, and intent keywords.
    """
    return {
        "schema_version": 2,
        "updated_at": "2026-09-06T00:00:00Z",
        "review_expires_at": "2026-12-05T00:00:00Z",
        "registry": [{"id": crop.id, "aliases": list(crop.aliases)} for crop in CROPS.values()],
        "disclaimer": DISCLAIMER,
        "keywords": list(_FERTILIZER_KEYWORDS),
        "crops": {
            crop_id: {
                "label": _CROP_LABEL[crop_id],
                "aliases": list(CROPS[crop_id].aliases),
                "available": NUMERIC_GUIDANCE_VERIFIED,
                "lines": (
                    list(recommendation["lines"])
                    if NUMERIC_GUIDANCE_VERIFIED
                    else [WITHHELD_NOTICE]
                ),
                "sources": (
                    [dict(source) for source in recommendation["sources"]]
                    if NUMERIC_GUIDANCE_VERIFIED
                    else []
                ),
            }
            for crop_id, recommendation in _RECOMMENDATIONS.items()
        },
    }


def is_fertilizer_query(text: str) -> bool:
    """True if the question is about fertilizer/fertilization."""
    t = (text or "").lower()
    return any(kw in t for kw in _FERTILIZER_KEYWORDS)


def _match_crop(text: str) -> str | None:
    """Return the fertilizer-supported crop id named in the text, or None.

    A recognized crop that lacks fertilizer data (soja, coton, riz, sésame, fonio)
    returns None so the caller can fall back to RAG.
    """
    crop = resolve_crop(text)
    if crop and crop.fertilizer_supported:
        return crop.id
    return None


def get_fertilizer_advice(
    text: str,
    *,
    crop: str | None = None,
    growth_stage: str = "",
    location: str = "",
) -> dict | None:
    """Return grounded fertilizer advice for the crop in the question.

    Returns a dict with answer, sources, and a structured evidence-first case when
    a supported crop is detected, otherwise None (so the caller can fall back to
    RAG). The numbers are fixed/cited — never generated — and the answer always
    carries the disclaimer.

    Optional ``crop`` (from the field-context form) is used when the free text
    does not name a crop.
    """
    named = resolve_crops(text)
    if len(named) > 1:
        labels = ", ".join(item.label_fr for item in named)
        return {
            "answer": (
                f"Vous avez cité plusieurs cultures ({labels}). Indiquez une seule "
                "culture pour éviter une mauvaise fumure."
            ),
            "sources": [],
            "case": None,
            "confidence": "Faible",
            "answer_kind": "clarification",
        }
    if named and not named[0].fertilizer_supported:
        return {
            "answer": (
                f"Je n’ai pas de dose d’engrais vérifiée pour le {named[0].label_fr}. "
                "Demandez conseil à un agent agricole local."
            ),
            "sources": [],
            "case": None,
            "confidence": "Faible",
            "answer_kind": "refusal",
        }

    matched = (named[0].id if named else None) or _match_crop(crop or "")
    if matched is None or matched not in _RECOMMENDATIONS:
        return None

    if not NUMERIC_GUIDANCE_VERIFIED:
        return {
            "answer": (
                f"Pour {_CROP_LABEL[matched]}, je ne peux pas encore donner une "
                f"dose exacte en toute sécurité.\n\n⚠️ {WITHHELD_NOTICE}"
            ),
            "sources": [],
            "case": None,
            "confidence": "Faible",
            "answer_kind": "refusal",
        }

    rec = _RECOMMENDATIONS[matched]
    sources = [dict(src) for src in rec["sources"]]
    body = "\n".join(f"• {line}" for line in rec["lines"])
    answer = (
        f"🌱 Fumure recommandée pour {_CROP_LABEL[matched]} au Burkina Faso :\n"
        f"{body}\n\n"
        f"{DISCLAIMER}"
    )
    do_not = [
        "N'augmentez pas les doses sans conseil local.",
        "Évitez l'urée juste avant une forte pluie si possible.",
    ]
    if matched in {"niebe", "arachide"}:
        do_not.append("Évitez les fortes doses d'urée sur les légumineuses.")

    case = build_advice_case(
        answer=answer,
        question=text,
        input_type="fertilizer",
        crop=CROPS[matched].label_fr,
        growth_stage=growth_stage,
        location=location,
        sources=sources,
        confidence="Fort",
        summary=f"Fumure recommandée pour {_CROP_LABEL[matched]} au Burkina Faso.",
        evidence=[src.get("snippet", "") for src in sources],
        actions=list(rec["lines"]),
        do_not=do_not,
        disclaimer=DISCLAIMER,
        confirmation=(
            "Confirmez toujours avec votre agent agricole : la bonne dose dépend "
            "de votre sol, de la pluie et de vos moyens."
        ),
        risk_level="Faible si confirmé localement",
    )
    return {"answer": answer, "sources": sources, "case": case}
